name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install requirements
        run: | 
          python -m pip install --upgrade pip
          pip install pytest setuptools wheel twine
          pip install -r requirements.txt

      - name: Install package
        run: |
          python setup.py install

      - name: Test
        run: pytest

      - name: Run examples
        run: |
          python examples/create_frame.py
          python examples/read_frame.py

      - name: Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          path: dist/ldfparser*.whl

      - name: Publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*