name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov setuptools wheel
          pip install -r requirements.txt

      - name: Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: dist/

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
